AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: Globally unique name for the S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private  # Options: Private | PublicRead | PublicReadWrite, etc.
      VersioningConfiguration:
        Status: Enabled       # Enables versioning on the bucket

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref MyS3Bucket
